version: '3.8'

services:
  profile:
    image: ${DOCKER_USERNAME}/profile-service:latest
    container_name: profile-service-container
    ports:
      - '3002:3002'
    environment:
      - APP_PORT: ${APP_PORT}
      - APP_CLIENT: ${APP_CLIENT}
      - MONGO_CONNECTION_STRING: ${MONGO_CONNECTION_STRING}
      - JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
